<a href="https://colab.research.google.com/github/Saurav-S-Mehta-07/PythonClasses/blob/main/DL/neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neuron

In [1]:
import torch
import torch.nn as nn

In [12]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0,2.0,3.0])

In [13]:
neuron = nn.Linear(in_features=3, out_features=1)

In [14]:
output = neuron(inputs)

In [15]:
print(output)
print(neuron.weight)
print(neuron.bias)

tensor([1.5244], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)
Parameter containing:
tensor([0.5304], requires_grad=True)


In [16]:
# verify -- formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)