# \# <i> NumPy </i>

In [ ]:
import numpy as np

In [ ]:
py_list = [1,2,3,4,5]

np_arr = np.array(py_list)

np_arr

array([1, 2, 3, 4, 5])

In [7]:
# twice the elements 
py_list = [i*2 for i in py_list]
py_list

np_arr = np_arr*2
np_arr
print(np_arr.dtype)

int64


## creating numpy array::::

In [9]:
# numpy array
arr = np.array([1,2,3,4]) #1d array
print(arr, arr.dtype, arr.shape, arr.ndim)

arr = np.array([[1,2,3],[4,5,6]]) # 2d array (2 x 3)
print(arr, arr.dtype, arr.shape, arr.ndim)



[1 2 3 4] int64 (4,) 1
[[1 2 3]
 [4 5 6]] int64 (2, 3) 2


In [7]:
import numpy as np
arr = np.zeros((2,3), dtype="int64") # arr with zeros
arr # array
arr.shape # 2 x 3
arr.ndim #dimension
arr.size # no. of element
arr.dtype # datatype

dtype('int64')

In [9]:
arr = np.ones((2,3), dtype="int64") # arr with all 1s
arr

array([[1., 1., 1., 1., 1.]])

In [11]:
arr = np.full((3,4),100) # prefill with value
arr

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [14]:
arr = np.eye((3), dtype="int32") # identity matrix
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [19]:
arr = np.arange(1,11,2) # range (start, end, step)
print(arr)

[1 3 5 7 9]


In [23]:
arr = np.linspace(1,100,3, dtype="int64") # evely space array
print(arr)

[  1  50 100]


## properties of numpy arrays

In [28]:
import numpy as np

arr = np.array([1,2,3,4,5])

arr.shape # 1 x 5
arr.dtype # datatype
arr.ndim # dimension
arr.size # no. of element

float_arr = arr.astype(np.float64) # type casting
float_arr


array([1., 2., 3., 4., 5.])

## Operations on NumPy arrays

In [31]:
# reshaping
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [32]:
# flatened an array (2d - 1d)
arr = np.array([[1,2,3],[4,5,6]])
flattened = arr.flatten()
print(flattened, flattened.shape)

[1 2 3 4 5 6] (6,)


In [33]:
#indexing
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])

1
2


In [36]:
# fancy indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,2]
print(arr[idx])
print(arr[[0,2,4]])

[1 2 3]
[1 3 5]


In [38]:
# boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr>2])

print(arr[arr%2==0])

[3 4 5]
[2 4]


In [39]:
# slicing
arr = np.array([1,2,3,4,5])
sliced = arr[1:4] # slice but real view  not just a copy 
print(sliced)
sliced[0] = 99
print(arr)

[2 3 4]
[ 1 99  3  4  5]


In [41]:
# copy
arr = np.array([1,2,3,4,5])
sliced = arr[1:4].copy()
print(sliced)
sliced[0] = 100
print(sliced)
print(arr)

[2 3 4]
[100   3   4]
[1 2 3 4 5]


# common datatype in numpy arrays

In [49]:
arr = np.array([1,2,3,4,5])
arr.dtype

arr = np.array([1.1,2,3,4])
arr.dtype

arr = np.array([1,2,"a","abc"]) # 1st all converts to string
arr.dtype

arr1 = np.array([3+4j])
arr1.dtype

arr2 = np.array([2+3j])
arr2.dtype

print(arr1+arr2)
print(arr1-arr2)

arr = np.array(["saurav", {1,2,3,"a",4}])
print(arr.dtype)

[5.+7.j]
[1.+1.j]
object


# <i> Axes in Multi-dimensional arrays </i>

In [52]:
# 1d array
arr_1d = np.array([1,2,3,4,5])
total = np.sum(arr_1d)
print(total)

15


In [67]:
# 2d array
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

arr_2d[0][1] # 2
arr_2d[0,1] # 2

total_sum = np.sum(arr_2d)
print(total_sum)

sum_of_columns = np.sum(arr_2d, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr_2d, axis = 1)
print(sum_of_rows)

sliced = arr_2d[0:2, 1:2]
print(sliced)

arr_2d

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
# 3d array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
arr_3d.ndim

print(arr_3d[0][1][1]) # 5
print(arr_3d[0,1,1]) # 5

sliced = arr_3d[:,0,:] #1st row from each layer
print(sliced)

sliced = arr_3d[:,:,0]
print(sliced) #1st col from each layer


sum_of_layer1 = np.sum(arr_3d, axis = 0)
print(sum_of_layer1)

arr_3d[:,:,0] = 0 # manupulating the elements


5
5
[[1 2 3]
 [7 8 9]]
[[1 4]
 [7 1]]
[[ 6 15]
 [24  6]]


# \# <i> Vectorization </i>

In [84]:
arr = np.array([1,2,3,4,5])
arr

arr = arr ** 2
arr

arr = arr + 5
arr

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1 + arr2

array([ 7,  9, 11, 13, 15])

# \# <i> Broadcasting </i>

In [86]:
arr = np.array([1,2,3,4,5])
arr + 5 # 5 -> [5,5,5,5,5]

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

arr + arr2

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

# \# <i> Vector Normalization </i>


In [92]:
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)
normalized_arr = (arr-mean)/std # mean of normalized arr is 0
normalized_arr

print(normalized_arr.mean())
print(normalized_arr.std())


# column wise normalization

mean = np.mean(arr, axis = 0)
std = np.std(arr, axis = 0)
normalized_arr = (arr-mean)/std 
normalized_arr

print(normalized_arr.mean())
print(normalized_arr.std())

0.0
1.0
0.0
1.0


# \# <i> Mathematical functions </i>

In [121]:
arr = np.array([1,2,3,4,5])
print("sum : ", np.sum(arr))
print("mean : ", np.mean(arr))
print("median : ", np.median(arr))
print("standard deviation : ", np.std(arr))
print("variance : ", np.var(arr))
print("max val : ", np.max(arr))
print("min val : ", np.min(arr))
print("product : ", np.prod(arr))
print("argmin : ", np.argmin(arr))
print("argmax : ", np.argmax(arr))
print("square : ", np.square(arr))
print("square root : ", np.sqrt(arr))
print("power : ", np.pow(arr,2))
print("log : ", np.log(arr))
print("log 10 : ", np.log10(arr))
print("log 2 : ", np.log2(arr))
print("exponential : ", np.exp(arr))
print("round : ", np.round(1.222))
print("floor : ", np.floor(1.222))
print("ceil : ", np.ceil(1.222))
print("truncate : ", np.trunc(1.222))
print("sort : " , np.sort(arr))
print("reverse sort : ", np.sort(arr)[::-1])
print("absolute : ", np.abs(-2.2))
print("unique : ", np.unique(arr))

sum :  15
mean :  3.0
median :  3.0
standard deviation :  1.4142135623730951
variance :  2.0
max val :  5
min val :  1
product :  120
argmin :  0
argmax :  4
square :  [ 1  4  9 16 25]
square root :  [1.         1.41421356 1.73205081 2.         2.23606798]
power :  [ 1  4  9 16 25]
log :  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log 10 :  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
log 2 :  [0.         1.         1.5849625  2.         2.32192809]
exponential :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
round :  1.0
floor :  1.0
ceil :  2.0
truncate :  1.0
sort :  [1 2 3 4 5]
reverse sort :  [5 4 3 2 1]
absolute :  2.2
unique :  [1 2 3 4 5]
